// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Author struct {
	ID        string     `json:"id"`
	FirstName *string    `json:"firstName"`
	LastName  string     `json:"lastName"`
	Birthday  *time.Time `json:"birthday"`
	Books     []*Book    `json:"books"`
}

type AuthorInput struct {
	ID        string  `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  string  `json:"lastName"`
}

type Book struct {
	Isbn    string    `json:"isbn"`
	Title   string    `json:"title"`
	Authors []*Author `json:"authors"`
	Year    *int      `json:"year"`
}

type BookInput struct {
	Isbn    string         `json:"isbn"`
	Title   string         `json:"title"`
	Authors []*AuthorInput `json:"authors"`
	Year    *int           `json:"year"`
}

type CreateAuthorInput struct {
	FirstName *string      `json:"firstName"`
	LastName  string       `json:"lastName"`
	Books     []*BookInput `json:"books"`
}
